### ISSUE TITLE
Use DVC for test data

### ISSUE THREAD

**Issue by pdiakumis** [umccr/gpgr#41]
```
mamba install -c conda-forge dvc dvc-gdrive
dvc init
dvc add file.txt
dvc remote add -d storage gdrive://<...>
dvc push
dvc pull

# use previous version
git checkout ...
dvc checkout

dvc list
dvc get https://github.com/umccr/gpgr inst/extdata # use dvc import for tracking
```

Links:

- https://github.com/iterative/dvc
- https://dvc.org/doc/start/data-and-model-versioning
- https://dvc.org/doc/start/data-and-model-access
- https://github.com/iterative/cml#using-cml-with-dvc (GH Action)

**Comment by pdiakumis** [comment]
Closing since this doesn't fit the way R pkgs are built, which generally requires all example data to be in the git source.

**Comment by pdiakumis** [comment]
Perhaps set up a test suite via GitHub Actions that pulls DVC'ed test data from a Google Drive and runs a set of tests on those.

**Comment by victorskl** [comment]
Me, watching this space! 😁
