### ISSUE TITLE
Empty LINX annotations causes crash

### ISSUE THREAD

**Issue by scwatts** [umccr/gpgr#66]
- The LINX module crashes during table parsing when provided empty LINX annotations
- This is caused by `order` trying to process an empty vector in `gpgr:::mixedrank` 
- Empty LINX annotations can be expected where no SVs/CNVs are present or detected in a sample
- A patch to allow report generation in this scenario is given below (plotting section remains empty with no message)

There are few ways to handle empty LINX annotation inputs, the below patch only avoids the crash and generates an empty report. Let me know if this is suitable from your perspective and I can submit a PR if you like. Example report created with patch attached.

<br />

<details><summary>Click to show command and error</summary>

<br />Command:

> Input generated from COLO829 BAMs sliced to genes present in TSO500, provided by Hartwig

```bash
Rscript gpgr/inst/cli/gpgr.R linx \
  --sample COLO829T \
  --plot data/no_annotations/plots/ \
  --table data/no_annotations/annotations/ \
  --out 2_no_annotations/COLO829T.linx_report.html
```

Log of stdout/stderr:

```text
── Start rendering LINX R Markdown report! ────────────────────────────────────────────────────────────────────────────────────────────


processing file: linx.Rmd
  |..........................                       |  53% [vis_copy_number]
Quitting from lines 210-214 [vis_copy_number] (linx.Rmd)
Error in `dplyr::arrange()`:
ℹ In argument: `..1 = mixedrank(.data$Chrom)`.
Caused by error in `order()`:
! argument 1 is not a vector
Backtrace:
  1. DT::formatCurrency(...)
 18. gpgr:::mixedrank(.data$Chrom)
 19. base::order(gtools::mixedorder(x))

Execution halted
```

</details>

<details><summary>Click to show possible fix</summary>

```diff
diff --git a/R/utils.R b/R/utils.R
index 17050e2..7dfb492 100644
--- a/R/utils.R
+++ b/R/utils.R
@@ -247,5 +247,7 @@ cpdir <- function(from, to) {

 # https://stackoverflow.com/a/61647053/2169986
 mixedrank <- function(x) {
-  order(gtools::mixedorder(x))
+  if (length(x) > 0) {
+    order(gtools::mixedorder(x))
+  }
 }
```

</details>

<br />

Attachments: [COLO829T.linx_report.gpgr_patched.html.gz](https://github.com/umccr/gpgr/files/12210386/COLO829T.linx_report.gpgr_patched.html.gz)

**Comment by pdiakumis** [comment]
Wait, I don't handle empty files properly? So sorry about that, I'll push a fix probably later today. Can you attach that empty file too please?

**Comment by scwatts** [comment]
Empty input files are definitely in corner case territory for LINX!

**Attachment**: [no_annotations.tar.gz](https://github.com/umccr/gpgr/files/12210607/no_annotations.tar.gz)
