### ISSUE TITLE
Update umccr cancer gene panel for PURPLE gene subset

### ISSUE THREAD

**Issue by pdiakumis** [umccr/gpgr#75]
Still using https://github.com/umccr/genes/blob/893a655801ce92715f05517b5052e4e81904e870/panels/umccr_2019-03-20.tsv based on <https://github.com/umccr/gpgr/blob/14c1f5e03e010007d25759981fd8640ce25c2064/R/purple.R#L63>.

@scwatts do we point that instead to one of the panels in https://github.com/umccr/gene_panels?

**Comment by scwatts** [comment]
Missed that but makes sense to me. The [latest GH release](https://github.com/umccr/gene_panels/releases/tag/v24.03.0) is a good place to grab the somatic panel, which has the columns/data needed.

**Comment by pdiakumis** [comment]
This one is okay I presume, since it has symbol plus the oncogene + tsgene status:
https://github.com/umccr/gene_panels/blob/v24.03.0/somatic_panel/3_final_panel/final_panel.tsv

**Comment by scwatts** [comment]
Yep! For each release I also include the 'final' panels as a release asset if you have a preference e.g. `somatic_panel-v24.03.0.tsv` in the [v24.03.0 release](https://github.com/umccr/gene_panels/releases/tag/v24.03.0)
